### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by TeaBear5** [BluemarkInnovations/RemoteID-MQTT-subscriber#1]
I am not able to connect to the ds230 unit after following the instructions.  I have updated the newest firmware version and ran the dronescout binary.  Could you provide any guidance? Here is the result when running dronescout on the device side:

```
root@ds01240100000298:~# ./dronescout.arm64 
DroneScout
open drone ID detector
2021 - 2023 Bluemark Innovations BV
version: 20240108-1539

Settings:
sensorID: ds01240100000298
use the first dBm RSSI value instead of the strongest signal 0
use db_ant_signal radiotap value for RSSI 0
log tags to file: 0
verbose level: 0

MQTT settings
transmit mode: 2
aggregate data: 1
compression: lzma
transmit mode 2 interval ms: 250
retain: 0
host: localhost
port: 1883
topic: /sensor/ds01240100000298/upload
QoSlevel: 1
username: 
password: 
keepalive: 60
clientID: ds01240100000298
SSL mode: 0
SSL verify: 0
SSL CA file: /root/certs/ca.crt
SSL CRT file: /root/certs/client.crt
SSL KEY file: /root/certs/client.key
interface WLAN 1: wlx30eb1f4d9d32
interface WLAN 2: wlx30eb1f4d9c65
interface BT UART 1: /dev/ttyACM0
interface BT USB 1: hci0
threshold_WLAN_USB: -200 dBm
threshold_BT_UART: -200 dBm
threshold_BT_USB: -200 dBm
mqtt localhost 1883 60
WARNING: unable to connect.
```

In the 60 seconds before this closes I am running the mqtt_sub.py script on my Ubuntu 22.04 system which immediately fails with the following error:

```
➜  RemoteID-MQTT-subscriber git:(main) ✗ sudo python3 mqtt_sub.py
Traceback (most recent call last):
  File "/home/tyler/Workspace/Lighthouse/RemoteID-MQTT-subscriber/mqtt_sub.py", line 153, in <module>
    run()
  File "/home/tyler/Workspace/Lighthouse/RemoteID-MQTT-subscriber/mqtt_sub.py", line 148, in run
    client = connect_mqtt()
  File "/home/tyler/Workspace/Lighthouse/RemoteID-MQTT-subscriber/mqtt_sub.py", line 59, in connect_mqtt
    client.connect(config.broker, config.port)
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

Here is my config.py file:
```
➜  RemoteID-MQTT-subscriber git:(main) ✗ cat config.py 
#!/usr/bin/python3
# (c) Bluemark Innovations BV
# MIT license
# settings file

import random

#MQTT broker settings
broker = '192.168.0.129'
port = 1883
topic = "#"

# generate client ID with pub prefix randomly
client_id = f'mqtt-subscriber-{random.randint(0, 100)}'

#optional user/password for connecting to the MQTT broker, uncomment if used.
# username = 'root'
# password = 'bluemark'

#file containing full SSL chain, uncomment when MQTT broker uses encrypted messages [preferred]
#client_pem = "./certs/client.pem"

# save the detected Remote ID signals to a CSV file in the log_path folder
# uncomment to enable logging
# log_path = './logs'
```

Any guidance on this would be greatly appreciated.  As far as I can tell I am doing everything as instructed.

**Comment by BluemarkInnovations** [comment]
Hi, fastest support is by sending an email to info@bluemark.io 
Of course, no problem to post an issue here.

- Normally the dronescout.arm64 application is already started when you boot the device. It is in the screen DRONESCOUT. 
 
```
root@ds221000000230:~# screen -R
There are several suitable screens on:
        3014.DUMMY      (01/24/2024 11:34:49 AM)        (Detached)
        3010.WATCHDOG   (01/24/2024 11:34:49 AM)        (Detached)
        3000.REMOTE     (01/24/2024 11:34:49 AM)        (Detached)
        2997.DRONESCOUT (01/24/2024 11:34:49 AM)        (Detached)
```

It can be accessed via `screen -R DRONESCOUT` If you run it twice there will be unexpected behavior as the application is started twice.

In the latest firmware 20240108-1539, the application provides MQTT debugging output in file /tmp/mqtt.log

If successful, the latest line in this file reads "INFO MQTT: connecting and publishing data". In the latest [manual](https://download.bluemark.io/ds230.pdf), the different MQTT error codes are described in the section troubleshooting.

So having said above:

- the application is killed, because likely the watchdog scripts detects an error and as a result will kill all dronescout applications.
- I assume that IP address 192.168.0.129 is the IP address of the sensor. Is so, did you follow the steps in 2.5 of the [manual](https://download.bluemark.io/ds230.pdf) to install the MQTT broker on the sensor? If you installed it on another device, please make sure it allows anonymous connections i.e. add "listener 1883" and "allow_anonymous true" to the mosquitto.conf file. In the default setup the MQTT broker is not installed due to security concerns. (If it is not used, it is better to have it not installed by default.)
- The error `ConnectionRefusedError: [Errno 111] Connection refused` typically means that the script cannot connect to the MQTT broker.

**Comment by TeaBear5** [comment]
Thanks!  I was able to get connected and am receiving the status message every minute.  Is this result in the DRONESCOUT screen a concern?

```
QoSlevel: 1
username:
password:
keepalive: 60
clientID: ds01240100000298
SSL mode: 0
SSL verify: 0
SSL CA file: /root/certs/ca.crt
SSL CRT file: /root/certs/client.crt
SSL KEY file: /root/certs/client.key
interface WLAN 1: wlx30eb1f4d9d32
interface WLAN 2: wlx30eb1f4d9c65
interface BT UART 1: /dev/ttyACM0
interface BT USB 1: hci0
threshold_WLAN_USB: -200 dBm
threshold_BT_UART: -200 dBm
threshold_BT_USB: -200 dBm
mqtt localhost 1883 60
sh: 1: ubus: not found
Create monitor thread
Create license thread
Create wlan1 thread
Create wlan2 thread
create wlan hopping thread
channel index 0 | 1
channel index 1 | 2
channel index 2 | 3
channel index 3 | 4
channel index 4 | 5
channel index 5 | 6
channel index 6 | 44
channel index 7 | 149
channel index 8 | 7
channel index 9 | 8
channel index 10 | 9
channel index 11 | 10
channel index 12 | 11
channel index 13 | 13
channel index 14 | 6
channel index 15 | 149
channel index 16 | 44
channel index 17 | 36
channel index 18 | 40
channel index 19 | 48
channel index 20 | 52
channel index 21 | 56
channel index 22 | 60
channel index 23 | 64
channel index 24 | 149
channel index 25 | 6
channel index 26 | 44
channel index 27 | 161
channel index 28 | 165
ls: cannot access '/proc/net/rtl8*/wlx30eb1f4d9d32/monitor': No such file or directory
INFO: device license activated!
ls: cannot access '/proc/net/rtl8*/wlx30eb1f4d9c65/monitor': No such file or directory
```

It also seems to crash the application when I connect to the DRONESCOUT screen.

**Comment by TeaBear5** [comment]
Was able to successfully receive remote ID data from a drone.

**Comment by BluemarkInnovations** [comment]
> Thanks! I was able to get connected and am receiving the status message every minute. Is this result in the DRONESCOUT screen a concern?
> 
> ```
> ......
> threshold_WLAN_USB: -200 dBm
> threshold_BT_UART: -200 dBm
> threshold_BT_USB: -200 dBm
> mqtt localhost 1883 60
> sh: 1: ubus: not found
> Create monitor thread
> Create license thread
> Create wlan1 thread
> Create wlan2 thread
> create wlan hopping thread
> channel index 0 | 1
> ........
> ls: cannot access '/proc/net/rtl8*/wlx30eb1f4d9d32/monitor': No such file or directory
> INFO: device license activated!
> ls: cannot access '/proc/net/rtl8*/wlx30eb1f4d9c65/monitor': No such file or directory
> ..........
> ```
> 
> It also seems to crash the application when I connect to the DRONESCOUT screen.

No it does not crash, it is more debug information that normal users would not see. I included it in my answer to show you where the application was started already. Background, depending on the installed WLAN driver, the method of hopping to different WLAN channels is different. The above error message is a result of trying one of the methods.

**Comment by TeaBear5** [comment]
I think since I am unfamiliar with the screen command I may not using it properly, but when i attempt to attach to DRONESCOUT using `screen -R DRONESCOUT` it stops reporting to the MQTT subscriber.  Just wanted to point this out in case there was something not correct about this, but it is not an issue as long as i don't run that command.

Thanks again for the assistance.

**Comment by BluemarkInnovations** [comment]
Well, normally you don't need to do the ` screen -R DRONESCOUT` command. All mqtt debug info is in /tmp/mqtt.log. Having said that, to detach a screen, use this key combination: Ctrl+a followed by d. See this [link](https://askubuntu.com/questions/124897/how-do-i-detach-a-screen-session-from-a-terminal). Very likely you exited the screen instead.
